<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="FirebaseAdmin" Version="3.4.0" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Google.Apis.Auth" Version="1.72.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Polly" Version="8.6.4" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SME.SERAp.Prova.Dados\SME.SERAp.Prova.Dados.csproj" />
    <ProjectReference Include="..\SME.SERAp.Prova.Dominio\SME.SERAp.Prova.Dominio.csproj" />
    <ProjectReference Include="..\SME.SERAp.Prova.Infra\SME.SERAp.Prova.Infra.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="UseCase\ProvaSaoPaulo\Proficiencia\Aluno\TratarProeficienciaAlunoTratarUseCase.cs" />
    <Compile Remove="Commands\Ue\TrataSincronizacaoInstitucionalUe\TrataSincronizacaoInstitucionalUeCommand.cs" />
    <Compile Remove="UseCase\WorkerRabbit.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\Ue\TrataSincronizacaoInstitucionalUe\" />
  </ItemGroup>

</Project>
