CREATE TABLE IF NOT EXISTS PUBLIC.EXECUCAO_CONTROLE
(
    ID              INT8      NOT NULL GENERATED ALWAYS AS IDENTITY,
    ULTIMA_EXECUCAO TIMESTAMP NOT NULL,
    EXECUCAO_TIPO   NUMERIC   NOT NULL
);

ALTER TABLE PUBLIC.EXECUCAO_CONTROLE
    ADD CONSTRAINT EXECUCAO_CONTROLE_PK
        PRIMARY KEY (ID);

CREATE INDEX EXECUCAO_CONTROLE_TIPO_IDX
    ON PUBLIC.EXECUCAO_CONTROLE (EXECUCAO_TIPO);


INSERT INTO PUBLIC.EXECUCAO_CONTROLE (ULTIMA_EXECUCAO, EXECUCAO_TIPO)
values (current_timestamp, 1);

CREATE TABLE IF NOT EXISTS PUBLIC.PROVA
(
    ID              INT8         NOT NULL GENERATED ALWAYS AS IDENTITY,
    DESCRICAO       VARCHAR(255) NOT NULL,
    INICIO          TIMESTAMP    NOT NULL,
    FIM             TIMESTAMP    NOT NULL,
    INCLUSAO        TIMESTAMP    NOT NULL,
    TOTAL_ITENS     NUMERIC      NOT NULL,
    prova_legado_id INT8         NOT NULL
);

ALTER TABLE PUBLIC.PROVA
    ADD CONSTRAINT PROVA_PK
        PRIMARY KEY (ID);

CREATE INDEX PROVA_LEGADORID_IDX
    ON PUBLIC.PROVA (prova_legado_id);


CREATE TABLE IF NOT EXISTS PUBLIC.PROVA_ANO
(
    ID       INT8    NOT NULL GENERATED ALWAYS AS IDENTITY,
    ANO      NUMERIC NOT NULL,
    PROVA_ID INT8    NOT NULL
);

ALTER TABLE PUBLIC.PROVA_ANO
    ADD CONSTRAINT PROVA_ANO_PK
        PRIMARY KEY (ID);

CREATE INDEX PROVA_ANO_IDX
    ON PUBLIC.PROVA_ANO (ANO);

ALTER TABLE PUBLIC.PROVA_ANO
    ADD CONSTRAINT PROVA_ANO_PROVA_FK FOREIGN KEY (PROVA_ID) REFERENCES PUBLIC.PROVA (ID);


CREATE TABLE IF NOT EXISTS PUBLIC.QUESTAO
(
    ID                INT8         NOT NULL GENERATED ALWAYS AS IDENTITY,
    ORDEM             NUMERIC      NOT NULL,
    PERGUNTA          VARCHAR(255) NOT NULL,
    ENUNCIADO         VARCHAR(255) NOT NULL,
    PROVA_LEGADO_ID   INT8         NOT NULL,
    QUESTAO_LEGADO_ID INT8         NOT NULL,
    PROVA_ID          INT8         NOT NULL,
    INCLUSAO          TIMESTAMP    NOT NULL
);

ALTER TABLE PUBLIC.QUESTAO
    ADD CONSTRAINT QUESTAO_PK
        PRIMARY KEY (ID);

CREATE INDEX QUESTAO_LEGADO_PROVA_ID_IDX
    ON PUBLIC.QUESTAO (PROVA_LEGADO_ID);

CREATE INDEX QUESTAO_LEGADO_ID_IDX
    ON PUBLIC.QUESTAO (QUESTAO_LEGADO_ID);

ALTER TABLE PUBLIC.QUESTAO
    ADD CONSTRAINT QUESTAO_PROVA_FK FOREIGN KEY (PROVA_ID) REFERENCES PUBLIC.PROVA (ID);


CREATE TABLE IF NOT EXISTS PUBLIC.ALTERNATIVA
(
    ID                    INT8         NOT NULL GENERATED ALWAYS AS IDENTITY,
    ORDEM                 NUMERIC      NOT NULL,
    DESCRICAO             VARCHAR(255) NOT NULL,
    ALTERNATIVA           VARCHAR(10)  NOT NULL,
    CORRETA               BOOLEAN      NOT NULL,
    QUESTAO_ID            INT8         NOT NULL,
    PROVA_LEGADO_ID       INT8         NOT NULL,
    QUESTAO_LEGADO_ID     INT8         NOT NULL,
    ALTERNATIVA_LEGADO_ID INT8         NOT NULL,
    INCLUSAO              TIMESTAMP    NOT NULL
);

ALTER TABLE PUBLIC.ALTERNATIVA
    ADD CONSTRAINT ALTERNATIVA_PK
        PRIMARY KEY (ID);

CREATE INDEX ALTERNATIVA_LEGADO_PROVA_ID_IDX
    ON PUBLIC.ALTERNATIVA (PROVA_LEGADO_ID);

CREATE INDEX ALTERNATIVA_LEGADO_QUESTAO_ID_IDX
    ON PUBLIC.ALTERNATIVA (QUESTAO_LEGADO_ID);

CREATE INDEX ALTERNATIVA_LEGADO_ID_IDX
    ON PUBLIC.ALTERNATIVA (ALTERNATIVA_LEGADO_ID);

ALTER TABLE PUBLIC.ALTERNATIVA
    ADD CONSTRAINT ALTERNATIVAQUESTAO_PROVA_FK FOREIGN KEY (QUESTAO_ID) REFERENCES PUBLIC.QUESTAO (ID);