name: Docker Image CI - Development
 
on:

  push:
    branches: [ development ]
    paths-ignore:
    - ".github/workflows/**"  
  
  workflow_dispatch:

jobs:
   
  sonar:

    runs-on: master
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Sonar
        uses: luizhpriotto/action_images@sonarscanner-v1.0
        env:
          DOTNET_PROJECT: SME.SERAp.Prova.Worker.sln
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST: http://sonar.sme.prefeitura.sp.gov.br/
          SONAR_EXTRA_ARG: >
            /d:sonar.cs.opencover.reportsPaths='"teste/SME.SERAp.Aplicacao.Test/coverage.opencover.xml","teste/SME.SERAp.Dominio.Test/coverage.opencover.xml"'
            /d:sonar.coverage.exclusions='"**Test*.cs"'
   
  build:

    runs-on: master
    needs: [ sonar] 
    steps:
      - uses: actions/checkout@v2     
      -  name: Login to registry
         uses: docker/login-action@v1
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
    
      - name: Build the Docker image    
        run: | 
             docker build . --file src/SME.SERAp.Prova.Worker/Dockerfile --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-worker
             docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-worker
           
  deploy:
  
    runs-on: master
    needs: [ build ]    
    environment:
      name: development
    steps:
      - name: Redeploy
        uses: luizhpriotto/action_images@kubectl-v1.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: sme-prova-serap-worker
          NAMESPACE: sme-serap-estudante
